// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations'
    },
    // CLI / migrations talk to Supabase's direct (session-mode) URL. The runtime
    // adapter uses DATABASE_URL (transaction pooler) -- see src/lib/prisma.ts.
    datasource: {
        url: env('DIRECT_URL')
    }
});
